# Cloud Build configuration for deploying to Cloud Run
# Usage: gcloud builds submit --config cloudbuild.yaml

substitutions:
  _SERVICE_NAME: moengage-qna-agent-v2
  _REGION: asia-northeast3  # Seoul
  _GCS_BUCKET: mfl-solutions-moengage-qna-data
  _TAG: latest

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${_TAG}'
      - '.'

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${_TAG}'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${_TAG}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '3600'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '3'
      - '--no-cpu-throttling'
      - '--set-env-vars'
      - 'STORAGE_BACKEND=gcs,GCP_STORAGE_BUCKET=${_GCS_BUCKET},HISTORY_API_ENABLED=true,PYTHONUNBUFFERED=1,COMPLETE_EMOJI=완료'
      - '--update-secrets'
      - 'SLACK_BOT_TOKEN=slack-bot-token:latest,SLACK_APP_TOKEN=slack-app-token:latest,ANTHROPIC_API_KEY=anthropic-api-key:latest,CSM_RESPONSE_CHANNEL_ID=csm-response-channel-id:latest'

images:
  - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${_TAG}'

options:
  logging: CLOUD_LOGGING_ONLY
